[2025-05-27 12:37:51,059] ERROR django.security.DisallowedHost Invalid HTTP_HOST header: '192.168.0.197'. You may need to add '192.168.0.197' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.197'. You may need to add '192.168.0.197' to ALLOWED_HOSTS.
[2025-05-27 12:37:51,777] ERROR django.security.DisallowedHost Invalid HTTP_HOST header: '192.168.0.197'. You may need to add '192.168.0.197' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.197'. You may need to add '192.168.0.197' to ALLOWED_HOSTS.
[2025-05-27 12:37:52,033] ERROR django.security.DisallowedHost Invalid HTTP_HOST header: '192.168.0.197'. You may need to add '192.168.0.197' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/silpc065/SANJU/Food_Flash/food_flash_env/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.197'. You may need to add '192.168.0.197' to ALLOWED_HOSTS.
